# Generated by Django 4.1.5 on 2023-01-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0002_alter_photo_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=models.JSONField(help_text='Формат {"name": ["name"]}', null=True, verbose_name='Дополнительная информация к фото'),
        ),
    ]
